# Generated by Django 4.2.2 on 2023-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ManyToManyField(related_name='students_grades', to='students.grade'),
        ),
    ]
